### Create User
POST http://localhost:3000/user
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123",
    "name": "Test User"
}

### Get all users
GET http://localhost:3000/user

### Auth
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
}

### Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test1@example.com",
    "password": "password123",
    "name": "Test1 User"
}



### Get all words with filter
GET http://localhost:3000/dictionary/entries/en?search=car&limit=5

### Get all words with filter and pagination
GET http://localhost:3000/dictionary/entries/en?search=car&limit=5&page=2

### Get a specific word
GET http://localhost:3000/dictionary/entries/en/adenocarcinoma

### Favorite a word
PATCH http://localhost:3000/dictionary/entries/en/adenocarcinoma/favorite



